/**
 * Warm cream blur placeholder for Next.js <Image> placeholder="blur".
 * Used until real photography is provided.
 */
export const WARM_CREAM_BLUR =
  "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDiIVFhEYIxsbGiMfIiQmKiotJh8qJCouKy4wMzQ1NTAlP0E5OD9GPzI5NTD/2wBDAQoLCw4NDhgQEBgwIh8iMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDD/wAARCAABAAEDASIAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAACf/EABQQAQAAAAAAAAAAAAAAAAAAAAD/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AJQAB/9k=";
