// AUTO-GENERATED â do not edit manually
// Regenerate by running the portfolio manifest script
// Generated: 2026-06-26T15:46:18.914594Z

export const imageManifest: Record<string, string[]> = {
  'cherry-creek': [
    '/images/portfolio/cherry-creek/01-334-steele.jpg',
    '/images/portfolio/cherry-creek/02-334-steele.jpg',
    '/images/portfolio/cherry-creek/03-334-steele.jpg',
    '/images/portfolio/cherry-creek/04-334-steele.jpg',
    '/images/portfolio/cherry-creek/05-334-steele.jpg',
  ],
  'highlands/alcott': [
    '/images/portfolio/highlands/alcott/01-alcott.jpg',
    '/images/portfolio/highlands/alcott/02-alcott.jpg',
    '/images/portfolio/highlands/alcott/03-alcott.jpg',
    '/images/portfolio/highlands/alcott/04-alcott.jpg',
    '/images/portfolio/highlands/alcott/05-alcott.jpg',
  ],
  'highlands/mariposa': [
    '/images/portfolio/highlands/mariposa/01-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/02-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/03-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/04-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/05-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/06-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/07-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/08-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/09-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/10-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/11-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/12-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/13-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/14-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/15-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/16-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/17-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/18-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/19-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/20-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/21-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/22-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/23-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/24-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/25-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/26-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/27-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/28-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/29-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/30-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/31-mariposa.jpg',
    '/images/portfolio/highlands/mariposa/32-mariposa.jpg',
  ],
  'lakewood-cc': [
    '/images/portfolio/lakewood-cc/01-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/02-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/03-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/04-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/05-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/06-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/07-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/08-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/09-lakewood-cc.jpg',
    '/images/portfolio/lakewood-cc/10-lakewood-cc.jpg',
  ],
        };

// Flat list of every portfolio photo, for the gallery view.
// Each entry is [path, projectName] for hover labels.
export const galleryPhotos: Array<{ path: string; project: string }> = [
  { path: '/images/portfolio/cherry-creek/01-334-steele.jpg', project: '334 Steele Street' },
  { path: '/images/portfolio/cherry-creek/02-334-steele.jpg', project: '334 Steele Street' },
  { path: '/images/portfolio/cherry-creek/03-334-steele.jpg', project: '334 Steele Street' },
  { path: '/images/portfolio/cherry-creek/04-334-steele.jpg', project: '334 Steele Street' },
  { path: '/images/portfolio/cherry-creek/05-334-steele.jpg', project: '334 Steele Street' },
  { path: '/images/portfolio/highlands/alcott/01-alcott.jpg', project: 'Alcott Street' },
  { path: '/images/portfolio/highlands/alcott/02-alcott.jpg', project: 'Alcott Street' },
  { path: '/images/portfolio/highlands/alcott/03-alcott.jpg', project: 'Alcott Street' },
  { path: '/images/portfolio/highlands/alcott/04-alcott.jpg', project: 'Alcott Street' },
  { path: '/images/portfolio/highlands/alcott/05-alcott.jpg', project: 'Alcott Street' },
  { path: '/images/portfolio/highlands/mariposa/01-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/02-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/03-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/04-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/05-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/06-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/07-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/08-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/09-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/10-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/11-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/12-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/13-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/14-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/15-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/16-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/17-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/18-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/19-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/20-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/21-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/22-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/23-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/24-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/25-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/26-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/27-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/28-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/29-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/30-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/31-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/highlands/mariposa/32-mariposa.jpg', project: 'Mariposa' },
  { path: '/images/portfolio/lakewood-cc/01-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/02-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/03-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/04-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/05-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/06-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/07-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/08-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/09-lakewood-cc.jpg', project: 'Lakewood Country Club' },
  { path: '/images/portfolio/lakewood-cc/10-lakewood-cc.jpg', project: 'Lakewood Country Club' },
];

// Map: project id (from lib/constants.ts) -> manifest key
// Used by /portfolio-preview to look up images for a project
export const projectImageMap: Record<string, string> = {
  'cherry-creek-custom-home': 'cherry-creek',
  'cherry-creek-334-steele':  'cherry-creek',
  'cherry-hills-custom-home': 'cherry-creek',
  'highlands-mariposa':       'highlands/mariposa',
  'highlands-alcott':         'highlands/alcott',
  'highlands-sunnyside':      'highlands/sunnyside',
  'lakewood-cc-interior':     'lakewood-cc',
  'bow-mar-custom':           'bow-mar',
};
